# docker-compose.yml

version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "bookstore_db"
      MYSQL_ROOT_PASSWORD: "Clarusway_1"
      MYSQL_USER: "clarusway"
      MYSQL_PASSWORD: "Clarusway_1"
    networks:
      - bookstore
    volumes:
      - mysql-volume:/var/lib/mysql
  web:
    build: .
    restart: always
    networks:
      - bookstore
    ports:
      - "80:80"
    depends_on:
      - database
networks:
  bookstore:
    driver: bridge
volumes:
  mysql-volume: